CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Programs" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "ShortName" character varying(255) NOT NULL,
    "Description" text NULL,
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_Programs" PRIMARY KEY ("Id")
);

CREATE TABLE "Tags" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    CONSTRAINT "PK_Tags" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_Tags_Name" UNIQUE ("Name")
);

CREATE TABLE "Users" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(255) NOT NULL,
    "LastName" character varying(255) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "Hash" character varying(255) NULL,
    "IsAdministrator" boolean NOT NULL,
    "IsEventOrganizer" boolean NOT NULL,
    "IsRewardProvider" boolean NOT NULL,
    "Enabled" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Events" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "Location" character varying(255) NULL,
    "Description" text NULL,
    "StartTime" timestamp without time zone NOT NULL,
    "EndTime" timestamp without time zone NOT NULL,
    "OrganizerId" integer NOT NULL,
    "SubmitDate" timestamp without time zone NULL,
    "Review_IsApproved" boolean NULL,
    "Review_Comments" text NULL,
    "Review_Timestamp" timestamp without time zone NULL,
    "Review_ReviewerId" integer NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Events" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Events_Users_OrganizerId" FOREIGN KEY ("OrganizerId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Events_Users_Review_ReviewerId" FOREIGN KEY ("Review_ReviewerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Rewards" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "Description" text NULL,
    "NumOfEventsToQualify" integer NOT NULL DEFAULT 1,
    "ProviderId" integer NOT NULL,
    "SubmitDate" timestamp without time zone NULL,
    "ExpireDate" timestamp without time zone NULL,
    "Review_IsApproved" boolean NULL,
    "Review_Comments" text NULL,
    "Review_Timestamp" timestamp without time zone NULL,
    "Review_ReviewerId" integer NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Rewards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Rewards_Users_ProviderId" FOREIGN KEY ("ProviderId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Rewards_Users_Review_ReviewerId" FOREIGN KEY ("Review_ReviewerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Attendances" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EventId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Attendances" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_Attendances_EventId_UserId" UNIQUE ("EventId", "UserId"),
    CONSTRAINT "FK_Attendances_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Attendances_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EventTags" (
    "EventId" integer NOT NULL,
    "TagId" integer NOT NULL,
    CONSTRAINT "PK_EventTags" PRIMARY KEY ("EventId", "TagId"),
    CONSTRAINT "FK_EventTags_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EventTags_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES "Tags" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RewardEvents" (
    "RewardId" integer NOT NULL,
    "EventId" integer NOT NULL,
    CONSTRAINT "PK_RewardEvents" PRIMARY KEY ("RewardId", "EventId"),
    CONSTRAINT "FK_RewardEvents_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RewardEvents_Rewards_RewardId" FOREIGN KEY ("RewardId") REFERENCES "Rewards" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Attendances_UserId" ON "Attendances" ("UserId");

CREATE INDEX "IX_Events_OrganizerId" ON "Events" ("OrganizerId");

CREATE INDEX "IX_Events_Review_ReviewerId" ON "Events" ("Review_ReviewerId");

CREATE INDEX "IX_EventTags_TagId" ON "EventTags" ("TagId");

CREATE INDEX "IX_RewardEvents_EventId" ON "RewardEvents" ("EventId");

CREATE INDEX "IX_Rewards_ProviderId" ON "Rewards" ("ProviderId");

CREATE INDEX "IX_Rewards_Review_ReviewerId" ON "Rewards" ("Review_ReviewerId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200729010742_InitialSchema', '3.1.4');

