DROP TABLE IF EXISTS "RewardEvents";
DROP TABLE IF EXISTS "Rewards";
DROP TABLE IF EXISTS "Attendances";
DROP TABLE IF EXISTS "EventThemes";
DROP TABLE IF EXISTS "Events";
DROP TABLE IF EXISTS "Programs";
DROP TABLE IF EXISTS "Themes";
DROP TABLE IF EXISTS "Categories";

DROP TABLE IF EXISTS "AspNetRoleClaims";
DROP TABLE IF EXISTS "AspNetUserClaims";
DROP TABLE IF EXISTS "AspNetUserLogins";
DROP TABLE IF EXISTS "AspNetUserTokens";
DROP TABLE IF EXISTS "AspNetUserRoles";
DROP TABLE IF EXISTS "AspNetRoles";
DROP TABLE IF EXISTS "AspNetUsers";

DROP TABLE IF EXISTS "__EFMigrationsHistory";
